#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    autocomplete_method = "coc"
    automatic_update = true
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "monokai_pro"
    colorscheme_bg = "dark"
    default_indent = 4
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    filemanager = "defx"
    # webdevicons_enable = 1
    guifont = "Hack:h11"
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    statusline_unicode = false
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    enabled_formater = "prettier"
    vimcompatible = true
    project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '!node_packages/', 'GTAGS']

[[layers]]
name = 'core'
filetree_show_hidden = true
enable_filetree_gitstatus = true
enable_filetree_filetypeicon = true

[[layers]]
name = "default"

# Enable autocomplete layer
[[layers]]
name = "autocomplete"
#auto_completion_return_key_behavior = "complete"
auto_completion_return_key_behavior = "smart"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = "colorscheme"

[[layers]]
name = "shell"
default_position = "top"
default_height = 30

[[layers]]
name = "git"

[[layers]]
name = "VersionControl"

[[layers]]
name = "format"
format_on_save = true

[[layers]]
name = "ctrlp"

[[layers]]
name = "fzf"

[[layers]]
name = "gtags"
#gtagslabel = "uctags" # "pygments"

[[layers]]
name = "zettelkasten"

[[layers]]
name = "telescope"

[[layers]]
name = "treesitter"

[[layers]]
name = "gtags"
auto_update = false
ctags_bin = "global"
#gtagslabel = "uctags" # "pygments"

[[layers]]
name = "cscope"
auto_update = false

[[layers]]
name = "lang#go"

[[layers]]
name = "lang#c"
enable_clang_syntax_highlight = true

[[layers]]
name = "lang#cmake"

[[layers]]
name = "lang#javascript"

[[layers]]
name = "lang#markdown"

[[layers]]
name = "lang#rust"

[[layers]]
name = "lang#python"

#[[custom_plugins]]
#  repo = 'Xuyuanp/nerdtree-git-plugin'
#  merged = false

#[[custom_plugins]]
#  repo = 'ryanoasis/vim-devicons'
#  merged = false

[[custom_plugins]]
  repo = 'kristijanhusak/defx-icons'
  merged = false

[[custom_plugins]]
  repo = 'kristijanhusak/defx-git'
  merged = false

[[custom_plugins]]
  repo = 'tenfyzhong/tagbar-rust.vim'
  merged = false

[[custom_plugins]]
  repo = 'yegappan/taglist'
  merged = false

[[custom_plugins]]
  repo = 'liuchengxu/vista.vim'
  merged = false

[[custom_plugins]]
repo = 'phanviet/vim-monokai-pro'
merged = 0
