# -*- mode: ruby -*-
# vi: set ft=ruby :

$IP = "192.168.56.231"
$CPU = 1
$RAM = 1024

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.network "private_network", ip: $IP

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = $CPU
    vb.memory = $RAM
  end

  # config.vm.synced_folder "./share", "/share"

  ##### Activate, when you are at work #####
  # config.vm.synced_folder "./certs", "/certs"
  # config.vm.provision "shell", inline: "apt-get update"
  # config.vm.provision "shell" do |s|
  #   s.path = "certs/update.sh"
  # end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "ansible/playbook.yaml"
    ansible.limit = "all"
    ansible.verbose = "v"
    ansible.extra_vars = {
      # user: "vagrant",
    }
  end

end

