# -*- mode: ruby -*-
# vi: set ft=ruby :

$IP = "192.168.56.132"
$CPU = 1
$RAM = 1024

Vagrant.configure("2") do |config|
  config.vm.box = "freebsd/FreeBSD-13.2-RELEASE"
  config.vm.box_version = "2023.04.07"

  config.vm.network "private_network", ip: $IP

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = $CPU
    vb.memory = $RAM
  end

  # config.vm.synced_folder "./share", "/share"

  config.vm.provision "shell", inline: <<-SHELL
    pkg update -f
  SHELL

end

