# -*- mode: ruby -*-
# vi: set ft=ruby :

$IP = "192.168.56.143"
$CPU = 1
$RAM = 1024

Vagrant.configure("2") do |config|
  config.vm.box = "bento/freebsd-14.3"
  config.vm.box_version = "202510.26.0"

  # uncomment after the first vagrant up
  # config.vm.network "private_network", ip: $IP

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = $CPU
    vb.memory = $RAM
  end

  # config.vm.synced_folder "./share", "/share"

  # config.vm.provision "shell", inline: <<-SHELL
  #   pkg update -f
  # SHELL

end

