################################################################################
# NVM
################################################################################
- name: Install NVM
  become_user: "{{ user }}"
  git:
    repo: https://github.com/nvm-sh/nvm.git
    dest: "{{ ansible_env.HOME }}/.nvm"
    version: v0.39.5
################################################################################
# rc.d
################################################################################
- name: Create node rc.sh file
  become_user: "{{ user }}"
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/{{ item }}"
  with_items:
    - rc.d/node.sh
################################################################################
# Install Node
################################################################################
- name: Install Node
  become_user: "{{ user }}"
  shell: |
    source {{ ansible_env.HOME }}/.config/rc.d/node.sh
    nvm install {{ item }}
  args:
    executable: /usr/bin/bash
  with_list: "{{ version.node }}"
- name: "Default Node Version {{ version.node[0] }}"
  become_user: "{{ user }}"
  shell: |
    source {{ ansible_env.HOME }}/.config/rc.d/node.sh
    nvm alias default {{ version.node[0] }}
  args:
    executable: /usr/bin/bash
- name: Enable Yarn.js
  become_user: "{{ user }}"
  shell: |
    source {{ ansible_env.HOME }}/.config/rc.d/node.sh
    corepack enable
  args:
    executable: /usr/bin/bash
################################################################################

