################################################################################
- name: Update APT
  become: yes
  apt:
    update_cache: yes
- name: Extra Packages
  become: yes
  apt:
    name:
      - neofetch
      - highlight
      - tree
      - ripgrep # for nvim
      - unzip # for nvim
################################################################################
# bat
################################################################################
- name: bat
  block:
    - name: Install bat
      become: yes
      apt:
        name:
          - bat
    - name: Symlink of bat
      become_user: "{{ user }}"
      file:
        src: /usr/bin/batcat
        dest: "{{ ansible_env.HOME }}/.local/bin/bat"
        state: link
    - name: Create a bat themes directory
      become_user: "{{ user }}"
      file:
        path: "{{ ansible_env.HOME }}/.config/bat/themes"
        state: directory
    - name: Download bat themes
      become_user: "{{ user }}"
      git:
        repo: https://github.com/catppuccin/bat.git
        dest: /tmp/catppuccin_bat
    - name: Select bat themes
      become_user: "{{ user }}"
      find:
        path: /tmp/catppuccin_bat
        patterns: "*.tmTheme"
      register: bat_themes
    - name: Copy to themes
      become_user: "{{ user }}"
      copy:
        src: "{{ item.path }}"
        dest: "{{ ansible_env.HOME }}/.config/bat/themes"
      with_items: "{{ bat_themes.files }}"
    - name: Rebuild bat cache
      become_user: "{{ user }}"
      shell: |
        bat cache --build
      args:
        executable: /usr/bin/bash
    - name: Add bat themes
      become_user: "{{ user }}"
      blockinfile:
        path: "{{ ansible_env.HOME }}/.config/export.sh"
        create: yes
        block: |
          export BAT_THEME="Catppuccin-mocha"
        marker_begin: BAT_BEGIN
        marker_end: BAT_END
################################################################################
# fzf
################################################################################
- name: fzf # for nvim
  block:
    - name: Install fzf
      become: yes
      apt:
        name:
          - fzf
    - name: Create fzf rc.sh files
      become_user: "{{ user }}"
      copy:
        src: "{{ item }}"
        dest: "{{ ansible_env.HOME }}/.config/{{ item }}"
      with_items:
        - rc.d/fzf.bash
        - rc.d/fzf.zsh
################################################################################
# fd
################################################################################
- name: fd
  block:
    - name: Install fd
      become: yes
      apt:
        name:
          - fd-find
    - name: Symlink of fd
      become_user: "{{ user }}"
      file:
        src: /usr/bin/fdfind
        dest: "{{ ansible_env.HOME }}/.local/bin/fd"
        state: link
################################################################################
# ZSH plugins
################################################################################
- name: Add Plugins at zshrc
  become_user: "{{ user }}"
  blockinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    create: true
    block: |
      fzf
    marker_begin: PLUGINS_BEGIN
    marker_end: PLUGINS_END
  when: zsh | default(false) | bool
################################################################################

