# typewritten
export TYPEWRITTEN_SYMBOL="λ"
export TYPEWRITTEN_CURSOR="block"
# export TYPEWRITTEN_RELATIVE_PATH="adaptive"
export TYPEWRITTEN_RELATIVE_PATH="home"
# export TYPEWRITTEN_PROMPT_LAYOUT="singleline_verbose"
export TYPEWRITTEN_PROMPT_LAYOUT="pure_verbose"

