################################################################################
# Start
################################################################################
- name: Essential Packages
  become: yes
  apt:
    name:
      - build-essential
    update_cache: yes
################################################################################
# User's directories
################################################################################
- name: "Make {{ item }}"
  become_user: "{{ user }}"
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
  with_items:
    - .local/bin
    - .local/share
################################################################################
# Get all your settings in one place
################################################################################
- name: Make .config/rc.d
  become_user: "{{ user }}"
  file:
    path: "{{ ansible_env.HOME }}/.config/rc.d"
    state: directory
- name: Source rc.d
  become_user: "{{ user }}"
  blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    create: true
    block: |
      shopt -s nullglob
      for RC in "$HOME/.config/rc.d/"*.{sh,bash}; do
        source "${RC}"
      done
      shopt -u nullglob
    marker_begin: INIT_BEGIN
    marker_end: INIT_END
- name: Create default rc.sh files
  become_user: "{{ user }}"
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/{{ item }}"
  with_items:
    - rc.d/alias.sh
    - rc.d/export.sh
################################################################################
# Git
################################################################################
- name: Global .gitignore
  become_user: "{{ user }}"
  copy:
    src: git/global.gitignore
    dest: "{{ ansible_env.HOME }}/.gitignore"
- name: Git Configuration
  become_user: "{{ user }}"
  copy:
    src: git/init.gitconfig
    dest: "{{ ansible_env.HOME }}/.gitconfig"
################################################################################

