################################################################################
- name: Update APT
  become: yes
  apt:
    update_cache: yes
- name: Install Java
  become: yes
  apt:
    name: "openjdk-{{ item }}-jdk-headless"
  with_list: "{{ version.java }}"
################################################################################
# jenv
################################################################################
- name: Install jenv
  become_user: "{{ user }}"
  git:
    repo: https://github.com/jenv/jenv.git
    dest: "{{ ansible_env.HOME }}/.jenv"
################################################################################
# rc.d
################################################################################
- name: Create java rc.sh file
  become_user: "{{ user }}"
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/{{ item }}"
  with_items:
    - rc.d/java.sh
################################################################################
# Add Java
################################################################################
- name: Set JAVA_HOME
  become_user: "{{ user }}"
  shell: |
    source {{ ansible_env.HOME }}/.config/rc.d/java.sh
    jenv enable-plugin export
  args:
    executable: /usr/bin/bash
- name: Add Java versions
  become_user: "{{ user }}"
  shell: |
    source {{ ansible_env.HOME }}/.config/rc.d/java.sh
    find /usr/lib/jvm -maxdepth 1 -type d -regex ".*/java-[0-9]+-openjdk-.*" -exec jenv add {} \;
  args:
    executable: /usr/bin/bash
- name: "Default Java Version {{ version.java[0] }}"
  become_user: "{{ user }}"
  shell: |
    source {{ ansible_env.HOME }}/.config/rc.d/java.sh
    jenv global {{ version.java[0] }}
  args:
    executable: /usr/bin/bash
################################################################################
- name: Create a Maven directory
  become: yes
  file:
    path: /opt/maven
    state: directory
- name: Install Maven
  become: yes
  unarchive:
    remote_src: yes
    src: "https://dlcdn.apache.org/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.tar.gz"
    dest: /opt/maven
- name: Add Maven PATH
  become_user: "{{ user }}"
  blockinfile:
    path: "{{ ansible_env.HOME }}/.config/rc.d/java.sh"
    create: true
    block:
      export PATH="$PATH:/opt/maven/apache-maven-3.9.4/bin"
    marker_begin: MAVEN_BEGIN
    marker_end: MAVEN_END
################################################################################
- name: Create a Gradle directory
  become: yes
  file:
    path: /opt/gradle
    state: directory
- name: Install Gradle
  become: yes
  unarchive:
    remote_src: yes
    src: "https://github.com/gradle/gradle/releases/download/v8.3.0/gradle-8.3-bin.zip"
    dest: /opt/gradle
- name: Add Gradle PATH
  become_user: "{{ user }}"
  blockinfile:
    path: "{{ ansible_env.HOME }}/.config/rc.d/java.sh"
    create: true
    block:
      export PATH="$PATH:/opt/gradle/gradle-8.3/bin"
    marker_begin: GRADLE_BEGIN
    marker_end: GRADLE_END

