# -*- mode: ruby -*-
# vi: set ft=ruby :

$ip = "192.168.56.231"

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/mantic64"

  config.vm.network "private_network", ip: $ip

  config.vm.synced_folder "./certs", "/certs"
  config.vm.synced_folder "./share", "/share"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo Provision Ubuntu
  SHELL

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbook.yaml"
    ansible.limit = "all"
    ansible.verbose = "v"
    ansible.extra_vars = {
      username: "vagrant",
    }
  end

end
