# -*- mode: ruby -*-
# vi: set ft=ruby :

$IP = "192.168.56.231"
$CERT = "self.signed.pem"

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/mantic64"

  config.vm.network "private_network", ip: $IP

  config.vm.synced_folder "./certs", "/certs"
  config.vm.synced_folder "./share", "/share"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    if [ -z "$SSL_CERT_FILE" ]; then
      echo "Activate Certs!"
      echo "SSL_CERT_FILE=/certs/#{$CERT}" >> /etc/environment
      echo "ca_certificate=/certs/#{$CERT}" >> /etc/wgetrc
      cat "/certs/#{$CERT}" | tee -a /etc/ssl/certs/ca-certificates.crt > /dev/null
    else
      echo "Certs Already Activated."
    fi
  SHELL

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbook.yaml"
    ansible.limit = "all"
    ansible.verbose = "v"
    ansible.extra_vars = {
      username: "vagrant",
    }
  end

end
